// Profile defaults are measured, not invented — derived from 13 real tapes in
// popular repos. Distributions and sources: data/extracted-defaults.json.

export const PROFILES = {
  // Single-interaction "hero" GIF at the top of a README.
  // Big font cluster (22–28) from ggh/sptlrx/butterfish; GitHub-blend margin from ggh.
  hero: {
    FontSize: 26,
    Width: 1500,
    Height: 640,
    Padding: 24,
    Margin: 20,
    MarginFill: '"#0d1117"',
    BorderRadius: 10,
    Framerate: 30,
    TypingSpeed: "100ms",
    Theme: '"Catppuccin Mocha"',
    CursorBlink: "false",
  },
  // Full-screen TUI walkthrough. Small font cluster (14–16), HD dimensions
  // from diffnav/dblab/puffin/gomanagedocker.
  tui: {
    FontSize: 16,
    Width: 1600,
    Height: 900,
    Padding: 16,
    Framerate: 30,
    TypingSpeed: "100ms",
    Theme: '"Catppuccin Mocha"',
    CursorBlink: "false",
  },
};

export const DIMENSION_BOUNDS = {
  hero: { w: [1200, 1600], h: [480, 720] },
  tui: { w: [1600, 1920], h: [800, 1200] },
};

export const MIN_FONT_SIZE = { absolute: 14, hero: 22 };

export function renderHeader({ profile = "hero", output = "demo.gif", shell, requires = [] } = {}) {
  const p = PROFILES[profile];
  if (!p) throw new Error(`unknown profile: ${profile}`);
  const lines = [
    `# Generated by autotape — profile "${profile}"`,
    "# Defaults measured from 13 real tapes in popular repos (data/extracted-defaults.json)",
    `Output ${output}`,
  ];
  for (const req of requires) lines.push(`Require ${req}`);
  if (shell) lines.push(`Set Shell ${JSON.stringify(shell)}`);
  for (const [k, v] of Object.entries(p)) lines.push(`Set ${k} ${v}`);
  return lines.join("\n") + "\n";
}
